apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: project-atlas
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/github-run-id: "9999999"
        # Crucial: enable multiple containers
        run.googleapis.com/container-dependencies: '{"atlas-gateway": ["keysentry-sidecar", "cognito-sidecar", "identity-service-sidecar"]}'
        # Direct VPC Egress to reach internal VM IPs (like the database at 10.218.0.2)
        run.googleapis.com/vpc-access-egress: "private-ranges-only"
        run.googleapis.com/network-interfaces: '[{"network":"default","subnetwork":"default"}]'
    spec:
      containers:
        # --- The Ingress Gateway Container ---
        - image: gcr.io/project-atlas-501612/project-atlas:
          name: atlas-gateway
          ports:
            - containerPort: 8080
          env:
            - name: ATLAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: 
                  key: latest
          resources:
            limits:
              cpu: "1000m"
              memory: "512Mi"

        # --- Sidecar 1: KeySentry API ---
        - image: gcr.io/project-atlas-501612/keysentry-api:
          name: keysentry-sidecar
          env:
            - name: PORT
              value: "8001"
            - name: ATLAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: 
                  key: latest
          startupProbe:
            tcpSocket:
              port: 8001
            initialDelaySeconds: 2
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

        # --- Sidecar 2: Cognito API ---
        - image: gcr.io/project-atlas-501612/cognito-api:
          name: cognito-sidecar
          env:
            - name: PORT
              value: "8002"
            - name: ATLAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: 
                  key: latest
          startupProbe:
            tcpSocket:
              port: 8002
            initialDelaySeconds: 2
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

        # --- Sidecar 3: Identity Serice API ---
        - image: gcr.io/project-atlas-501612/identity-service:
          name: identity-service-sidecar
          env:
            - name: PORT
              value: "8003"
            - name: ATLAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: 
                  key: latest
          startupProbe:
            tcpSocket:
              port: 8003
            initialDelaySeconds: 2
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
